---
title: "Homework 3"
format: html
---

**Due:** Friday, September 25, 11:59pm on Canvas

**Homework grading and resubmissions:** Homework will be graded on completeness, correctness, and effort. If you make an honest, good-faith effort attempt at a question, but your submitted work has some important errors or is missing a component I think is necessary, I may ask you to *resubmit* your work after receiving feedback. Your grade for that question would then be based on your resubmission.


**Collaborators and AI statement:** At the top of your assignment, list any collaborators (Dr. Evans does not count -- he is a resource, not a collaborator), and provide an AI statement describing your use of AI to complete the questions. If you did not use AI in any way, let me know that too. If you did use AI, provide: the model used, the HW questions on which you used AI, and a summary of the ways in which AI provided assistance. As described in the syllabus, AI use is permitted on homework assignments, but submissions without a complete AI statement may not receive full credit.

## Data analysis

Complete the [Data analysis: battle of the bands](https://ciaran-evans-sta-712-notes.share.connect.posit.cloud/logistic_regression_exercises.html#data-analysis-battle-of-the-bands) assignment. This involves answering *all* questions in that section.

Some things to note:

* For this data analysis, I want you to write up your results in a short report. This does **not** have to be a full-length project report, but I do want the report to be in full sentences and paragraphs, including relevant figures and model results.

* Your final submission does **not** have to include every figure that you make in the process of analyzing the data (there are about 80 explanatory variables you might consider -- don't include 80 different plots!). It is ok to be selective about the figures you choose to include.


