---
title: "Homework 3"
format: html
---

**Due:** Friday, September 18, 11:59pm on Canvas

**Instructions:** For mathematical work, you may choose to either hand-write your work and submit a PDF scan, or type your work using LaTeX and submit the resulting PDF. For computational work, include all code and R output necessary to answer the questions, and submit as an html or pdf on Canvas.

See the course website for a [homework template](https://sta712-f26.github.io/homework/hw_template.tex) file and [instructions](https://sta712-f26.github.io/homework/latex_instructions/) on getting started with LaTeX and Overleaf.

**Homework grading and resubmissions:** Homework will be graded on completeness, correctness, and effort. If you make an honest, good-faith effort attempt at a question, but your submitted work has some important errors or is missing a component I think is necessary, I may ask you to *resubmit* your work after receiving feedback. Your grade for that question would then be based on your resubmission.


**Collaborators and AI statement:** At the top of your assignment, list any collaborators (Dr. Evans does not count -- he is a resource, not a collaborator), and provide an AI statement describing your use of AI to complete the questions. If you did not use AI in any way, let me know that too. If you did use AI, provide: the model used, the HW questions on which you used AI, and a summary of the ways in which AI provided assistance. As described in the syllabus, AI use is permitted on homework assignments, but submissions without a complete AI statement may not receive full credit.

## Questions

### "Balancing" classes in logistic regression?

Read the [introduction and motivation](https://ciaran-evans-sta-712-notes.share.connect.posit.cloud/logistic_regression_exercises.html#balancing-classes-in-logistic-regression) for the question of artificially "balancing" our two classes in logistic regression, and the [overview of simulations](https://ciaran-evans-sta-712-notes.share.connect.posit.cloud/simulations.html) in the supplementary notes. Then answer these questions.

1. [Assessing downsampling](https://ciaran-evans-sta-712-notes.share.connect.posit.cloud/logistic_regression_exercises.html#exr-balancing_sim_1)

2. [Collecting a balanced sample from the beginning](https://ciaran-evans-sta-712-notes.share.connect.posit.cloud/logistic_regression_exercises.html#exr-balancing_sim_2)

3. [Adjusting the intercept](https://ciaran-evans-sta-712-notes.share.connect.posit.cloud/logistic_regression_exercises.html#exr-prevalence_change_intercept) (This is very common in certain study designs!)

### Designing diagnostics

**Motivation:** practice thinking about model assumptions, and designing diagnostics that could be used to assess these model assumptions.

4. [Proposing diagnostics for a different model](https://ciaran-evans-sta-712-notes.share.connect.posit.cloud/logistic_regression_exercises.html#exr-log_binomial_diagnostics)

5. [Implementation and simulation](https://ciaran-evans-sta-712-notes.share.connect.posit.cloud/logistic_regression_exercises.html#exr-log_binomial_diagnostics_2)

### Interpreting AUC

**Motivation:** Deriving a useful probabilistic interpretation for the area under the ROC curve; further practice with sensitivity, specificity, and ROC curves.

See the [introduction](https://ciaran-evans-sta-712-notes.share.connect.posit.cloud/logistic_regression_exercises.html#interpreting-area-under-the-roc-curve) to this question, then answer the following.

6. [AUC](https://ciaran-evans-sta-712-notes.share.connect.posit.cloud/logistic_regression_exercises.html#exr-auc_probability)


